version: '3'

services:
    server:
        build: .
        expose: 
            - 8000
        ports:
            - 8000:8000
        command: node server.js

    client:
        build: ./client
        expose: 
            - 3000
        ports:
            - 3000:3000
        links:
            - server
            
        command: npm start